keys:
  - &master_key age1t0gga8pltprn6ggy6lfq73x5lt5yh2ctyarh000ejx4ahnlnh4kqr3ull7
  - &server02 age13cwyduwmygwryyq28tggpwx6eupja4ad8mdxyfcla9yncvuzya6sgd9qe6
  - &server01 age1j2wjd2dxw0kw7jssnkfr9nmfqeqgr38qcdwh4fhkadnvnndd8cns6z9208
  - &server01_file age10vttwn7ucjd92jp7mlkc7kam7g264wpxum0hkljulhgzv9la3atq4gef85
  - &server02_file age10dv7rs9w9u42evv26syqspnfd6pnsfvdqlz88uvfwzgvwzju95tsafw2y9

creation_rules:
  - path_regex: ^(common/default.sops.yaml)$
    key_groups:
      - age:
        - *master_key
        - *server02
        - *server01
  - path_regex: ^(system/system01/default.sops.yaml)$
    key_groups:
      - age:
        - *master_key
        - *server01
  - path_regex: ^(system/system01/extraSecrets.sops.yaml)$
    key_groups:
      - age:
        - *master_key
        - *server01
  - path_regex: ^(system/system01/user.sops.yaml)$
    key_groups:
      - age:
        - *master_key
        - *server01_file
  - path_regex: ^(system/system02/default.sops.yaml)$
    key_groups:
      - age:
        - *master_key
        - *server02
  - path_regex: ^(system/system02/extraSecrets.sops.yaml)$
    key_groups:
      - age:
        - *master_key
        - *server02
  - path_regex: ^(system/system02/user.sops.yaml)$
    key_groups:
      - age:
        - *master_key
        - *server02_file
